try {
    // some code that might throw an error
  } catch (error) {
    console.log('An error occurred:', error.message);
  }